# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    # - run: npm test

  deploy:
     runs-on: ubuntu-latest
     environment:
       name: production
       url: https://github.com
     steps:
     - uses: actions/checkout@v4
     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: 20.x
         cache: 'npm'
     - run: npm ci
     - run: npm run lint
     - run: echo $VITE_HELLO_WORLD
       env:
         VITE_HELLO_WORLD: ${{ vars.VITE_HELLO_WORLD }}
     - run: npm run build
       env:
         VITE_HELLO_WORLD: ${{ vars.VITE_HELLO_WORLD }}
     - name: Archive production artifacts
       uses: actions/upload-artifact@v4
       with:
         name: dist
         path: dist